[toolchain]
package_manager = "yarn"
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
capstone_omni_donate = "J7mBvVKt1XyqtwdtHpxGPTHQhua2rBRkqYkdEopT3bhs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
upgrade_idl = "anchor idl upgrade J7mBvVKt1XyqtwdtHpxGPTHQhua2rBRkqYkdEopT3bhs -f ./target/idl/capstone_omni_donate.json" 